version: '3.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    expose:
      - '80'
      - '443'
    ports:
      - '10.0.0.27:80:80'
      - '10.0.0.27:443:443'
    environment:
      #- NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - type: bind
        source: nginx-certs
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    restart: unless-stopped
    command: ["nginx-debug", "-g", "daemon off;"]
    labels:
      cc.otaya.description: "OTAYA internal nginx reverse proxy."

networks:
  default:
    external:
      name: otaya-docker-net
