version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    expose:
      - '80'
      - '443'
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    environment:
      #- NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - nginx-certs:/etc/letsencrypt
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    restart: unless-stopped
    command: ["nginx-debug", "-g", "daemon off;"]
    labels:
      cc.otaya.description: "OTAYA internal nginx reverse proxy."

networks:
  default:
    name: otaya-docker-net
    external: true

volumes:
  nginx-certs:
    external: true
